baseurl = "http://www.suntong.cc"
title = "Tong"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Tong"
  info = "Embedded Software Development Engineer"
  description = "Tong's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "https://cdn.jsdelivr.net/gh/atongrun/ImageHost@main/202308222330847.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "X"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 1
  url = "https://x.com/atongrun/"
[[params.social]]
  name = "Ins"
  icon = "fa-brands fa-square-instagram fa-2x"
  weight = 2
  url = "https://www.instagram.com/atongrun/"
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 3
  url = "https://github.com/atongrun/"

# Menu links
[[menu.main]]
name = "Now"
weight = 1
url = "now/"
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"